# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, '[0-9]+.[0-9]+.x' ]
  pull_request:
    branches: [ master, '[0-9]+.[0-9]+.x' ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run lint:lib
    - run: npm run build:lib
    - run: npm run test:lib:others
      env:
        NODE_OPTIONS: --max_old_space_size=4096
    - run: npm run test:lib:grid
      env:
        NODE_OPTIONS: --max_old_space_size=4096
    - run: npm run test:lib:tgrid
      env:
        NODE_OPTIONS: --max_old_space_size=4096
    - run: npm run test:lib:hgrid
      env:
        NODE_OPTIONS: --max_old_space_size=4096
    - run: npm run test:schematics
    - name: Install coverage combiner
      if: github.repository == 'IgniteUI/igniteui-angular' && matrix.node-version == '14.x'
      run: sudo npm install -g istanbul-combine
    - name: Combine scripts
      if: github.repository == 'IgniteUI/igniteui-angular' && matrix.node-version == '14.x'
      run: istanbul-combine -d coverage -p none -r lcov -r cobertura coverage/hierarchical-grid/coverage-final.json coverage/tree-grid/coverage-final.json coverage/non-grid/coverage-final.json coverage/grid/coverage-final.json
    - name: Publish to coveralls.io
      if: github.repository == 'IgniteUI/igniteui-angular' && matrix.node-version == '14.x'
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ github.token }}

